Block/ExpressCheckoutMinicartButton.php, view/frontend/templates/express/button-minicart.phtml, view/frontend/web/js/checkout-button-minicart.js
* Removed requirement for an active quote
* Adjusted price update logic so it is updated as soon as it becomes initialized
=> Adjust minicart logic so it's added for new carts as well

Block/ExpressCheckoutMinicartButton.php, Model/Checkout/PlaceOrder.php, Model/Checkout/SetAmwalOrderDetails.php, Model/Config.php, Model/Config/Checkout/ConfigProvider.php, Plugin/Quote/Api/OverrideChangeQuoteValidation.php, ViewModel/ExpressCheckoutButton.php, composer.json, etc/adminhtml/system.xml, etc/config.xml, etc/di.xml, view/frontend/templates/express/button-listing.phtml, view/frontend/templates/express/button-minicart.phtml, view/frontend/templates/express/button.phtml, view/frontend/templates/lib/amwal-checkout-button-script.phtml, view/frontend/web/js/checkout-button-base.js, view/frontend/web/js/checkout-button-minicart.js, view/frontend/web/js/checkout-button-product.js, view/frontend/web/js/model/place-order.js, view/frontend/web/js/view/payment/amwal_payments.js, view/frontend/web/js/view/payment/method-renderer/amwal-payment.js
* Adjusted minicart button rendering logic so it gets added even when a quote is not created yet.
* Added possibility for Customer Creation on checkout with Amwal
* Don't allow zero total checkout (currently not supported)
* Post additional order details to Amwal on order placement
* General bugfixes + cleanup
* Updated Amwal checkout button library to version 0.0.34
=> Release - 1.0.7

composer.json, view/frontend/web/js/checkout-button-base.js
* Added fix to prevent "newquote" from being passed as a quote ID when no quote ID is known yet
=> Release 1.0.8

Model/Checkout/PlaceOrder.php, composer.json, view/frontend/web/js/checkout-button-base.js, view/frontend/web/js/model/place-order.js, view/frontend/web/js/view/payment/method-renderer/amwal-payment.js
Added handling for masked quote ID and several fixes for checkout process
=> Release - 1.0.9

view/frontend/requirejs-config.js, view/frontend/web/js/checkout-button-base.js, view/frontend/web/js/model/error-handler.js, view/frontend/web/js/model/pay-order.js, view/frontend/web/js/model/place-order.js
Implemented error handling through use of amwalPrePayTriggerError event
=> Feature | AMWAL-45 | Implement amwalPrePayTriggerError handling

Model/AddressResolver.php, Model/Checkout/GetQuote.php, Model/Checkout/InvoiceOrder.php, Model/Checkout/PlaceOrder.php, Model/Checkout/SetAmwalOrderDetails.php, Model/Checkout/UpdateShippingMethod.php, Model/Config.php, Model/Config/Checkout/ConfigProvider.php, Model/Data/AmwalOrderItem.php, Model/ThirdParty/CityHelper.php, ViewModel/ExpressCheckoutButton.php, view/frontend/web/js/checkout-button-base.js, view/frontend/web/js/view/payment/method-renderer/amwal-payment.js, view/frontend/web/template/payment/amwal-payment/form.html
Add missing options for regular checkout and fix email validation issue
=> AMWAL-92 | AMWAL-96 | Regular checkout

Model/AddressResolver.php
Ensure phone number formatting is also applied to existing linked addresses
=> AMWAL-83 | Phone number validation

Model/Checkout/PayOrder.php
In the order response you will now find:
```
"payment_additional_info": [
{
"key": "method_title",
"value": "Checkout with Amwal"
},
{
"key": "paymentBrand",
"value": "VISA"
}
],
```
=> AMWAL-95 | Add payment brand to additional info for order payment

Model/Checkout/GetQuote.php, view/frontend/web/js/checkout-button-base.js, view/frontend/web/js/checkout-button-product.js
* Use add to cart during pre checkout trigger
* Retrieve quote after adding to cart to ensure values are updated
=> AMWAL-104 | Use add to cart logic during pre checkout trigger

Model/Checkout/AmwalCheckoutAction.php, Model/Checkout/CleanQuote.php, Model/Checkout/GetQuote.php, Model/Checkout/InvoiceOrder.php, Model/Checkout/PayOrder.php, Model/Checkout/PlaceOrder.php, Model/Checkout/SetAmwalOrderDetails.php, Model/Checkout/UpdateShippingMethod.php, Model/ErrorReporter.php
Harmonizes error handling through an abstraction of the amwal checkout actions, and adds a call which reports error to the amwal backend for easier investigation of issues
=> AMWAL-131 - Add additional error reporting

Model/Checkout/GetQuote.php
Set quote 'is customer guest' to true if no customer id is set
=> AMWAL-165 - Magento 2.4.0 quote compatibility

Model/Checkout/PayOrder.php, Model/Checkout/PlaceOrder.php, Plugin/Sales/Order/Email/PreventEmailForNewOrder.php, etc/di.xml
Added a plugin to ensure order emails are only sent on successful payment
=> AMWAL-168 - Only send order emails on successful payment

view/frontend/templates/express/checkout-button.phtml
=> AMWAL-220 fill initial fields for final checkout

etc/view.xml
Add view.xml to indicate REACT dist folder should be excluded from JS merge
=> Exclude REACT dist folder form JS merge

Model/Button/GetCartButtonConfig.php, Model/Button/GetConfig.php, Model/ThirdParty/CityHelper.php
=> WIP - Localized city names

Model/Checkout/PlaceOrder.php
Always set Amwal client email address on quote + address if available and different from the current email
=> Always set Amwal client email address on quote + address

CHANGELOG.md, composer.json
This reverts commit 4898dafa91778a2dd3ac3f568181bc22fb865c2f.
=> Revert "1.0.25 (#160)"

CHANGELOG.md, composer.json
=> 1.0.25 (#166)

Model/Button/GetCartButtonConfig.php
Reverts amwal-tech/amwal-magento#204
=> Revert "Change addRegularCheckoutButtonConfig to public method "

Model/Data/OrderUpdate.php
=> Add order dataValidation

.dev-tools/.php-cs-fixer.php, .dev-tools/README.md, .dev-tools/composer.json, .dev-tools/phpstan.neon, .dev-tools/psalm.xml, .github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/sca.yml, .vscode/tasks.json, Api/Data/AmwalAddressInterface.php, Api/Data/AmwalButtonConfigInterface.php, Block/Widget/ExpressCheckoutButton.php, Model/Button/GetCartButtonConfig.php, Model/Checkout/GetQuote.php, Model/Checkout/PlaceOrder.php, Model/Config.php, Model/Data/AmwalOrderDetails.php, Model/Data/OrderUpdate.php, Plugin/RestApiCors.php, Plugin/Sentry/SentryExceptionReport.php, composer.json
- https://github.com/vimeo/psalm
- https://github.com/phpstan/phpstan
- https://github.com/php-cs-fixer/shim
- https://github.com/ergebnis/composer-normalize
- https://github.com/kubawerlos/composer-smaller-lock
- https://github.com/nektos/act
1. Go to Settings > Tools > External Tools.
2. Click + to add a new tool.
3. Name it (`GitHub Actions (act)`).
4. Set Program to your `act` executable path or just act if it's in your system `PATH`.
5. Set Arguments to the commands you typically use, like `-P ubuntu-latest=catthehacker/ubuntu:act-latest`.
6. Optionally, set the Working directory to `$ProjectFileDir$/app/code/Amwal/Payments/`.
7. Now, you can run act from Tools > External Tools > GitHub Actions (act).
1. Go to the` .vscode` directory in your project and create a `tasks.json` file if …
=> GitHub actions

Model/Data/OrderUpdate.php
```
{
"message": "Order (3000000054) base_grand_total does not match Amwal Order total_amount (27.2000 != 102.00)",
"trace": "#0 /var/www/html/app/code/Amwal/Payments/Model/Data/OrderUpdate.php(98): Amwal\\Payments\\Model\\Data\\OrderUpdate->dataValidation(Object(Magento\\Sales\\Model\\Order\\Interceptor), Object(Magento\\Framework\\DataObject))\n#1 /var/www/html/app/code/Amwal/Payments/Model/Checkout/PayOrder.php(107): Amwal\\Payments\\Model\\Data\\OrderUpdate->update(Object(Magento\\Sales\\Model\\Order\\Interceptor), 'PayOrder', false)\n#2 [internal function]: Amwal\\Payments\\Model\\Checkout\\PayOrder->execute(62, '4825bbf3-9eb3-4...')\n#3 /var/www/html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#4 …
```
=> fix the email subject and totals check.

Model/Checkout/PlaceOrder.php, Plugin/Sales/Order/SalesOrderGridPlugin.php, Test/Unit/Model/Checkout/PlaceOrderTest.php, Ui/Component/Listing/Column/TriggerContextOptions.php, etc/db_schema.xml, etc/db_schema_whitelist.json, view/adminhtml/ui_component/sales_order_grid.xml
=> Add Order Position

view/frontend/layout/checkout_onepage_success.xml, view/frontend/templates/success/success.phtml
=> Add installments instruction to order success page.

.github/workflows/config/integration-test-post-install.sh, .github/workflows/config/integration-tests-pre-install.sh, .github/workflows/integration-tests.yml, composer.json
Moves dev requirements to require-dev and add's a pre-install script to make sure the requirements are installed for integration testing
=> Update dev requirements

.github/workflows/integration-tests.yml, Model/AddressResolver.php, Model/Checkout/GetQuote.php
Adds an integration test run for Magento 2.4.3 with PHP 7.4
=> Add additional integration test version

Model/Checkout/GetQuote.php
**Screenshots**
Cart Price Rules 
1. SA:
2. EG:
=> GetQuote available rates code refactor 

Model/Button/GetCartButtonConfig.php
…all image URL or an empty string if no image is available.
=> Fixed product image URL retrieval to ensure it returns the correct small image URL or an empty string if no image is available.

Model/Button/GetCartButtonConfig.php
@ahmardi This might work in a more dynamic way
=> Dynamic attribute data gathering for configurable products

Model/Button/GetCartButtonConfig.php
Refactor order content product data to dynamically handle custom attributes
- Enhanced `getProductName` method to dynamically handle multiple custom attributes.
- Added type hints and comments for better readability.
- Simplified ternary operator for total calculation in `getProductData`.
- Ensured configurable product children are correctly handled.
=> Refactor product data methods to dynamically handle custom attributes

Model/Settings.php, Test/Integration/CheckoutFlowTest.php
Refactor the logic for converting JSON to arrays aligning it with Magento’s standard API data return.
=> Refactor Settings return data

Model/Config.php, Model/Config/Frontend/PluginVersion.php, Model/Settings.php, etc/adminhtml/system.xml
=> Add plugin version and Git commit info to Developer Settings

ViewModel/ExpressCheckoutButton.php
Refactors the isExpressCheckoutActive method to hide the checkout button if the GrandTotal is zero.
=> Adjust GrandTotal Check in isExpressCheckoutActive Method

Model/Checkout/GetQuote.php, Model/Checkout/PlaceOrder.php, Model/Config.php, etc/adminhtml/system.xml, etc/config.xml
=> add quote virtual items support

Model/Validator.php, Plugin/ConfigPlugin.php, etc/di.xml
=> Add text validator plugin

README.md
=> Update Workflows badge

Model/Settings.php
=> Add amwal_canceled_orders_update and cancelled_orders count with list of ids

README.md
=> Update README.md to include badges linked to specific integration test jobs

Model/Button/GetCartButtonConfig.php
…onal format using country code
=> Update GetCartButtonConfig.php to ensure phone number is in international format using country code

view/frontend/web/js/view/payment/amwal_payments.js
Ensure isRegularCheckoutActive is properly checked before adding the payment method to rendererList.
=> Refactor isRegularCheckoutActive check in amwal_payments.js

Plugin/Sentry/SentryExceptionReport.php
- Updated SentryExceptionReport to use Sdk::getCurrentHub()->configureScope() instead of Sentry\configureScope()
- Ensured proper initialization of Sentry SDK before reporting exceptions
- Improved reliability and compatibility with newer Sentry SDK versions
=> Replace deprecated Sentry\configureScope with Sdk::getCurrentHub

Api/Data/WebhookResponseInterface.php, Api/WebHookInterface.php, Block/Adminhtml/System/Config/CreateApiKey.php, Block/Adminhtml/System/Config/PrivateKeyStatus.php, Block/Adminhtml/System/Config/WebhookEvents.php, Block/Adminhtml/System/Config/WebhookUrl.php, Controller/Adminhtml/Webhook/CreateApiKey.php, Model/Config.php, Model/Config/Frontend/PluginVersion.php, Model/Data/WebhookResponse.php, Model/Event/HandlerFactory.php, Model/Event/HandlerInterface.php, Model/Event/OrderFailed.php, Model/Event/OrderSuccess.php, Model/Settings.php, Model/Webhook.php, Model/WebhookHelper.php, etc/adminhtml/routes.xml, etc/adminhtml/system.xml, etc/db_schema.xml, etc/di.xml, etc/webapi.xml, view/adminhtml/templates/system/config/create_api_key.phtml
Implements webhook functionality to notify external systems when orders succeed or fail.
This feature enables real-time notifications for successful orders, immediate alerts for failed orders, and integration capabilities with third-party services.
=> Add Order Status Webhooks for Success and Failure Events

view/frontend/templates/product/promotion.phtml
- Custom modal overlay with CSS isolation
- Dynamic iframe generation
- Browser back button integration
- Enhanced responsive design
- Performance optimizations"
=> refactor Amwal modal with theme isolation and browser history support

Block/Product/View/Promotion.php, view/frontend/templates/product/promotion.phtml
Added product validation and price formatting methods to Promotion block. Refactored frontend JS for better error handling, grouped product support, and modal management. Improved reliability and user experience by handling edge cases and providing safer DOM operations.
=> Enhance promotion logic and improve JS robustness

Block/Product/View/Promotion.php, view/frontend/templates/product/promotion.phtml
Introduces CurrencyConverter to convert product prices to SAR in Promotion block. Updates the number of installments from 6 to 12. In the promotion template, updates the Amwal widget script to use the latest version, enables debug mode, and cleans up widget attributes.
=> Add currency conversion and update promotion widget

Model/Settings.php, etc/webapi.xml, view/frontend/layout/checkout_index_index.xml, view/frontend/templates/lib/amwal-checkout-button-script.phtml, view/frontend/templates/product/promotion.phtml, view/frontend/web/js/view/checkout/sidebar/promotion.js, view/frontend/web/template/checkout/sidebar/promotion.html
Introduces a new Amwal promotion widget in the checkout sidebar by adding a Knockout.js component and template. Adds a new API endpoint to provide currency settings for the widget, updates layout XML to include the widget, and ensures the Amwal checkout button script is loaded globally. Removes redundant script inclusion from the product promotion template.
=> Add Amwal promotion widget to checkout sidebar
